### ISSUE TITLE
reactive params not firing when staletime is set

### ISSUE THREAD

**Issue by BhaskaranR** [DamianOsipiuk/vue-query#102]
I have the initialdata and stale time set. but QueryFunction does not get the callback when reactive params change.

```
const { data } = useQuery(
  reactive(["ITRQuery", { countPerPage }]),
  () =>
    getITRResult({
      ...props.condition,
      countPerPage: countPerPage.value,
    }),
  reactive({
    initialData: props.dto,
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
    retry: false,
    staleTime: twentyFourHoursInMs,
    useErrorBoundary: true,
  })
);
```
i had to either comment out initialData or staleTime which i don't want to do.

**Comment by DamianOsipiuk** [comment]
Hi,
This is working correctly.
Basically when you are setting `initialData` for `useQuery` you are saying i have a valid data for that query and it gets saved to the cache. Also by setting `staleTime` you are saying that data in the cache is valid for a specified period of time.

So when you are combining both of it, and change the query key by reactive property following happens:
- new query key -> create new query cache with new key
- we get initial data, so set it up as a cache value for that new key
- we get staleTime set so initialData will be valid for the time set in staleTime

This way when you change the key every time you get new cache entry it will be valid for staleTime from the time it got created.

To make it work the way you want you might want to explore the following:
- setting [initialDataUpdatedAt](https://react-query.tanstack.com/reference/useQuery) along initial data, so queryCache will not when your data gets stale
- use `placeholderData` instead of initialData - this will give you data available initially, but also issue fetch at the same time to get fresh data from server
- use [Infinite Queries](https://vue-query.vercel.app/#/guides/infinite-queries) that is slightly better in handling paginated data
- set data directly by calling [queryClient.setQueryData](https://react-query.tanstack.com/reference/QueryClient#queryclientsetquerydata) for a particular query key, so you would not set the same thing for every new key

If you would not succeed with those, please leave a message with more description of what you want to achieve so we could explore other options.

**Comment by BhaskaranR** [comment]
thanks for the prompt reply. works fine with setQueryData.
