### ISSUE TITLE
Default Options seems to not work

### ISSUE THREAD

**Issue by henry-chris** [DamianOsipiuk/vue-query#133]
Vue 3 + Vite

Main.ts example

```
import {VueQueryPlugin, VueQueryPluginOptions} from "vue-query";

const vueQueryPluginOptions: VueQueryPluginOptions = {
  queryClientConfig: {
    defaultOptions: {
      queries: {
        refetchOnWindowFocus: false,
        refetchOnMount: false,
        retry: false
      },
    },
  },
}

const setupApp = () => {
  const app = createApp(App).use(VueQueryPlugin, vueQueryPluginOptions)
};
```

Use query composable:

```
import axios from 'axios'
import {GetAccountDetailsResponse, GetAccountResponse, GetSubscriptionResponse} from "../models/AccountModels"
import { useQuery } from "vue-query"


export default function() {
  // These requests rely on the id in the auth token
  const getAccount = (): Promise<GetAccountResponse> => axios.get('/account')

  const getAccountDetails = (): Promise<GetAccountDetailsResponse> => axios.get('/account/details')

  return {
    getAccount: useQuery<GetAccountResponse, Error>('account', getAccount),
    getAccountDetails: useQuery<GetAccountDetailsResponse, Error>('accountDetails', getAccountDetails),
  }
}
```

Script in a component:

```
<script setup lang="ts">
import useSubscriptionManagerApi from "../composables/useSubscriptionManagerApi";
import useScreenModes from "../composables/useScreenModes";
import Content from '../components/default/Content.vue'

const { mobileMode } = useScreenModes()
const { getAccount } = useSubscriptionManagerApi()

const { isLoading, isError, isFetching, data, error, refetch } = getAccount

</script>
```

The getAccount query is called multiple times, and is still called on every window focus.

If I think set the options per query it works as intended.

**Comment by DamianOsipiuk** [comment]
Hi, I have added config that you have provided (`vueQueryPluginOptions`) to [basic example](https://github.com/DamianOsipiuk/vue-query/tree/main/examples/basic) and everything works as intended.

What might be happening if you have used `vue-query` before, is that you have added `VueQueryPlugin`, but somewhere in your code usage of `useQueryProvider` still exists which overwrites the plugin client.

If this is not the case, then i would have to ask you for a minimal reproducible repository, cause otherwise i would not be able to pinpoint the issue.

**Comment by henry-chris** [comment]
Welp, you are 100% correct.  We must have missed `useQueryProvider` when first setting it up.

Thank you very much, closing.
