### ISSUE TITLE
Reactivity

### ISSUE THREAD

**Issue by gutorsantos** [DamianOsipiuk/vue-query#139]
I'm working on a Vue project and I tried to use vue-query. However, I ended up encountering this behavior:

When I use 
```
const { isLoading, isError, data, error } = useGetResidencialByAnoMes(anomes, 10, filters)
```

it works normally, i can access the properties of data both in setup() and in template

But when I use:
```
const test = useGetResidencialByAnoMes(anomes, 10, filters)
```
And try access, for example, test.data.foo in setup() I get undefined and in template is not rendering anything. I tested to run a v-for loop in test.data and the reactivity properties are displayed (__object, __v_isRef).

I fixed that wrapping with reactive, like this:
```
const test = reactive(useGetResidencialByAnoMes(anomes, 10, filters))
```
But shouldn't it work without it?

**Comment by DamianOsipiuk** [comment]
Hi,
Composables exposed by `vue-query` library return all attributes as `refs`.
This means that `isLoading`, `data` etc. are all `refs`.
To get the actual value of `data` you need to access it's like `data.value`.
Therefore if you do not spread the returned object you should access your data like `test.data.value`.

Reasoning for returning refs instead of reactive object is that reactivity is lost whenever someone spreads such object. Therefore this would not work
`const { isLoading, isError, data, error } = useGetResidencialByAnoMes(anomes, 10, filters)`

Your fix works, because wrapping `refs` object with `reactive` uwraps all refs that are inside and it's a valid solution.

Another solution will be compiler syntax sugar which is currently still in RFC phase https://github.com/vuejs/rfcs/discussions/369

**Comment by gutorsantos** [comment]
Reactivity some time feels a little bit confusing to me, I'll try study to understand these behaviors.

Thanks for the answer!
