### ISSUE TITLE
[Bug Report] 'Error: Dynamic require of "vue-demi" is not supported' when trying to add VueQueryDevTools to nuxt3

### ISSUE THREAD

**Issue by Zenthae** [DamianOsipiuk/vue-query#141]
when adding the DevTools in the app, it crash, here is a repro https://github.com/Zenthae/vue-query-bug

**Comment by Zenthae** [comment]
- Deleted `. nuxt`and `node_modules`
- Run `pnpm vue-demi-fix`
- Switched to `vite@2.6.14` as stated in #127 
- SSR on/off
- Moved the plugin from both to the client and server side
- `Transport: ['vue-query']`

None of the above fixed the problem, now I'm out of idea.

Issue aside wouldn't using the official devtools be better ? since it has a wide compatibility range won't it remove this type of bug ?

**Comment by DamianOsipiuk** [comment]
So the issue in this case is this line: https://github.com/DamianOsipiuk/vue-query/blob/main/devtools/index.js#L12

This is there to treeshake DevTools in production builds without any additional code required from the user side.
This was not a problem so far, but i guess it is now.

I'm not really sure how to handle it right now. Would need to play with it to find a suitable solution.

---

React-query devtools are also exposed as a sub-package currently and they require react to work.
If you mean Vue Devtools, then you are more than welcome to create a plugin. It would be a great contribution that would probably remove a lot of boilerplate from the repo that is here due to Vue2 compatibility.

**Comment by DamianOsipiuk** [comment]
So this would be actually blocked by https://github.com/vuejs/devtools/discussions/1811

**Comment by DamianOsipiuk** [comment]
@Zenthae Your problem should be solved with [v1.21.0](https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.21.0)
Vue Query is now integrated with official Vue Devtools.

**Comment by Zenthae** [comment]
Insane ! 🥳
