### ISSUE TITLE
how to use refetch in useQueries ?

### ISSUE THREAD

**Issue by loktarjugg** [DamianOsipiuk/vue-query#195]
I need to periodically call useQueries, how can I do it?

**Comment by DamianOsipiuk** [comment]
Hi,
If you need to do that at some time interval, you could use [refetchInterval](https://react-query.tanstack.com/reference/useQuery) option on the specific query (number or function returning a number).
And you can do the same with `useQueries` since it uses the same options signature as `useQuery`.
