### ISSUE TITLE
Best Practise for working with a store?

### ISSUE THREAD

**Issue by veryard** [DamianOsipiuk/vue-query#202]
Hey,

Very curious about using this package, I just have a quick question to as if there is any examples or best practices to get this package working with a store eg. Pinia or Vuex.

Example of my store with an action:

```js
actions: {
        async fetchEmployees({ page = 1, search = "" }) {
            const { isLoading, data, error } = useFetch(
                ['employees', page, search],
                `/api/employees?page=${page}&search=${search}`
            )

            this.loading = computed(() => isLoading.value);
            this.error = computed(() => error.value);
            this.employees = computed(() => data.value?.data);
        }
}


// useFetch function
export function useFetch(key, url, options = {}) {
    return useQuery(key, () => 
        axios(url, options)
            .then(res => res.data)
    );
}
```

And my component looks something like: 

```html
<script setup>
import { useEmployeesStore } from "@/store/employees";

useHead({
    title: "Manage Employees",
});

const store = useEmployeesStore();
const employees = computed(() => store.employees);

await store.fetchEmployees({});
</script>
```

If I rerun the `store.fetchEmployees({})` I end up getting this error:
<img width="616" alt="Screen Shot 2022-07-01 at 9 03 10 pm" src="https://user-images.githubusercontent.com/3941758/176980971-ebdb269e-d22b-46b2-8989-c59fdaf358a6.png">

I know that you return a `refetch` from the `useQuery` function am just curious to as if you or anyone has a better approach to this.

Thanks.

**Comment by DamianOsipiuk** [comment]
I think the best practice would be to NOT use it with pinia, vuex or any other client state library (pushing state from vue-query to local state). [You can still use pinia for your client state, that is totally fine](https://vue-query-next.vercel.app/#/guides/does-this-replace-client-state).


Vue-query does fetching, caching, deduping etc. automatically for you and it should serve as your `store` for async data.
It will simply remove all the wiring and boilerplate you have to write.
You have even dedicated [devtools](https://vue-query-next.vercel.app/#/getting-started/devtools) that should help you explore what queries reside in cache and all the state about them. 

You can / should abstract specific calls as a wrapper functions that would make it easier to reuse:

```ts
export function useEmployeesQuery(page, search, options = {}) {
    return useQuery(['employees', page, search], () => 
        axios(`/api/employees?page=${page}&search=${search}`, options)
            .then(res => res.data)
    );
}
```

And you can call this function from whatever component you would like, and the rest will be handled by the library.
If you set longer `staleTime`, it will not refetch until `staleTime` is met, even if you mount new components or remount current ones.
If you mount multiple components on a page using the same query, they will send only one request.
etc. etc.


So instead of 
```ts
const store = useEmployeesStore();
const employees = computed(() => store.employees);

await store.fetchEmployees({});
```

You should just do:
```ts
const query = useEmployeesQuery(page, search)
const employees = computed(() => query.data?.value);
```

And it will fetch the data when needed.

**Comment by veryard** [comment]
Ah awesome, I had spent a bit more time playing around and came to this conclusion. Appreciate the speedy response and great job on the package.

Thanks again!
