### ISSUE TITLE
Vue Query is not deduping requests

### ISSUE THREAD

**Issue by RickEyre** [DamianOsipiuk/vue-query#234]
I am calling the same endpoint from different vue components in the app. They are making two separate requests, as seen in this screen shot. 

I was under the impression that vue query would be smart enough to only make one request?

<img width="1234" alt="Screen Shot 2022-08-30 at 2 52 50 PM" src="https://user-images.githubusercontent.com/1071332/187519216-fdcd3421-3e5a-42d7-9e2e-03994ee8adc6.png">

**Comment by DamianOsipiuk** [comment]
Could you post me the code, how you invoke those queries? 
Also check in Vue devtools if those two queries do not have different keys.

**Comment by kevin-courbet** [comment]
I am facing a similar issue... I understand React Query principles around Stale Time and Cache Time.
Ie the default behaviour is (simplified): 

1.  if data is stale, return cached data, refetch
2. if data is not stale, return cached data without fetching

Now the default stale time is 0 which means data is always considered stale. I wish to prevent unnecessary refetching by providing a stale time of let's say 5 minutes.

However, passing { staleTime: 1000 * 60 * 5 } (or Infinity) to useQuery or to Vue.use(VueQueryPlugin, { queries: { staleTime: Infinity } }) doesn't result in the expected behaviour that refetching won't happen.

I notice that in DevTools the query parameters don't seem to be affected at all? I tried changing the cached time and its stuck to its default value of 300000

My setup: Vue3, Vite

View (component) 1:
```ts
import { useAdmin } from '@/composables/admin';
const { getUsers } = useAdmin();
const { isLoading, data: profiles, suspense } = getUsers();
```

View (component) 2:
```
import { useAdmin } from '@/composables/admin';
const { getUsers } = useAdmin();
const { isLoading, data: profiles, suspense } = getUsers();
```

composable:
```ts
export const useAdmin = () => {
  const getUsers = () => {
    const { getUsers } = useFunctions(); // firebase stuff
    return useQuery(['users'], async () => (await getUsers()).data, { staleTime: Infinity });
  };
```

Any idea what is happening?

**Comment by kevin-courbet** [comment]
After further debugging and looking at the other open issue about suspense, this seems to be due to the call to Suspense. Suspense forces the query execution. Not sure if this is the expected behaviour or not. In my case I can probably replace the call to suspense by a watch on isLoading or isFetching.

I am still getting weird DevTools results so will submit a separate issue for this.

**Comment by DamianOsipiuk** [comment]
@RickEyre If you still have a problem with that, could you provide a minimal reproducible repo?
It should not happen, unless there is a bug that I do not know about or you might have some small configuration error in your code.

**Comment by douira** [comment]
I have also observed that caching is not respected if suspense is used. With the new tanstack version if vue-query I can't get  any request to happen at all if I use suspense. (maybe a separate problem)
