### ISSUE TITLE
Resolving react-query.

### ISSUE THREAD

**Issue by jwahdatehagh** [DamianOsipiuk/vue-query#262]
Got an error because yarn auto-installed react-query v4.

```
✘ [ERROR] Could not resolve "react-query/core"

    node_modules/vue-query/lib/index.mjs:2:180:
      2 │ ...nt as QueryClient$1, QueryObserver, QueriesObserver, InfiniteQueryObserver, MutationObserver } from 'react-query/core';
        ╵                                                                                                        ~~~~~~~~~~~~~~~~~~
```

Had to add a custom resolution to my package.json... 
```json
"resolutions": {
  "react-query": "3.39.0"
}
```

**Comment by DamianOsipiuk** [comment]
Which version of `vue-query` are you using?
v1 has specified `"react-query": "^3.39.0",` as a dependency so i see no way of v4 installed here, unless due to some specific project setup or a bug in the package manager.
v2+ on the other hand depends on `"@tanstack/query-core": "^4.3.7",`.

So i do not think there is anything wrong in this package, unless you pinpoint what exactly is the issue.

**Comment by jwahdatehagh** [comment]
`vue-query@2.0.0-beta.1` still resolved to `react-query/core` for me via yarn.

Upgrading to `vue-query@2.0.0-beta.12` resolved this!

Thank you
