### ISSUE TITLE
isSuccess.value

### ISSUE THREAD

**Issue by fxjzz** [DamianOsipiuk/vue-query#277]
![image](https://user-images.githubusercontent.com/100555114/224475953-91f2573e-b9cc-44fe-bf90-d89151456d2b.png)
![image](https://user-images.githubusercontent.com/100555114/224475982-ccdac49c-f2a1-477a-bc18-132fa4efccf9.png)

Why does this happen？

**Comment by DamianOsipiuk** [comment]
This happens because onSuccess is called before listeners are notified.

`onSuccess` gets fresh data as a parameter.

https://github.com/TanStack/query/blob/main/packages/query-core/src/queryObserver.ts#L683

As a side note please migrate to https://github.com/TanStack/query/tree/main/packages/vue-query
